economy:
  starting-balance: 100.0
  fractional-digits: 2
  currency-singular: "доллар"
  currency-plural: "долларов"

messages:
  prefix: "&x&0&3&4&B&B&C&ls&x&1&1&5&C&C&4&lʏ&x&2&0&6&D&C&B&ls&x&2&E&7&E&D&3&lᴛ&x&3&D&9&0&D&B&lᴇ&x&4&B&A&1&E&3&lᴍ &x&6&8&C&3&F&2• &r&f"
  no-permission: "&cУ вас нет прав на использование этой команды!"
  player-not-found: "&cИгрок не найден или не в сети!"
  invalid-amount: "&cНеверная сумма!"
  not-enough-money: "&cУ вас недостаточно денег!"
  balance-self: "Ваш баланс: %balance%"
  balance-other: "Баланс игрока %player%: %balance%"
  pay-sent: "Вы отправили %amount% игроку %player%"
  pay-received: "Вы получили %amount% от игрока %player%"
  money-given: "Вы выдали %amount% игроку %player%"
  money-taken: "Вы забрали %amount% у игрока %player%"
  money-set: "Вы установили баланс %player% на %amount%"
  self-payment: "&cВы не можете отправить деньги себе!"
  usagepay: "&eИспользование: /pay <игрок> <сумма>"
  usagebalance: "&eИспользование: /balance [игрок]"
  usagegivemoney: "&eИспользование: /givemoney <игрок> <сумма>"
  usagetakemoney: "&eИспользование: /takemoney <игрок> <сумма>"
  usagesetmoney: "&eИспользование: /setmoney <игрок> <сумма>"
  transaction-success: "&aТранзакция успешно выполнена!"
  transaction-failed: "&cОшибка транзакции!"
  negative-balance: "&cБаланс не может быть отрицательным!"