economy:
  starting-balance: 100.0
  fractional-digits: 2
  currency-singular: "доллар"
  currency-plural: "долларов"
  autosave-interval: 300
storage:
  type: "MYSQL" # или "YAML"

database:
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "root"
  password: "yourpassword"

messages:
  prefix: "&x&0&3&4&B&B&C&ls&x&1&1&5&C&C&4&lʏ&x&2&0&6&D&C&B&ls&x&2&E&7&E&D&3&lᴛ&x&3&D&9&0&D&B&lᴇ&x&4&B&A&1&E&3&lᴍ &x&6&8&C&3&F&2• &r&f"
  no-permission: "У вас нет прав на использование этой команды!"
  player-not-found: "Игрок не найден или не в сети!"
  invalid-amount: "Неверная сумма!"
  not-enough-money: "У вас недостаточно денег!"
  balance-self: "Ваш баланс: &b&l%balance%"
  balance-other: "Баланс игрока &b&l%player%&r: &b&l%balance%"
  pay-sent: "Вы отправили &b&l%amount%&r игроку &b&l%player%"
  pay-received: "Вы получили &b&l%amount%&r от игрока &b&l%player%"
  money-given: "Вы выдали &b&l%amount%&r игроку &b&l%player%"
  money-taken: "Вы забрали &b&l%amount%&r у игрока &b&l%player%"
  money-set: "Вы установили баланс &b&l%player%&r на &b&l%amount%"
  self-payment: "Вы не можете отправить деньги себе!"
  usagepay: "Использование: &b&l/pay <игрок> <сумма>"
  usagebalance: "Использование: &b&l/balance <игрок>"
  usageeco: "Использование: &b&l/eco <give|set|take> <игрок> <сумма>"
  transaction-success: "Транзакция успешно выполнена!"
  transaction-failed: "Ошибка транзакции!"
  negative-balance: "Баланс не может быть отрицательным!"